routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Route::get("menu-list")->name("menu.index")->uses("MenuController@index");
Route::get("menu-list-recursive")->name("menu.index.recursive")->uses("MenuController@recursive");
Route::resource("pages","PageController");
Route::get("page/{slug}")->name("pages.detail")->uses("PageFrontController@index");
\App\LaravelMenuManager\Routes\Routes::get();

resources/views/_layout.blade.php
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    @yield("styles")
</head>

<body>
@yield("content")
</body>

<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js"></script>
@yield("scripts")

</html>

resources/views/edit.blade.php
@if($isCreate)
    <form action="{{route("pages.update",["id"=>$page->id])}}" method="POST">
        {{method_field("PUT")}}
@else
            <form action="{{route("pages.store")}}" method="POST">
@endif
    {{csrf_field()}}

    @foreach((new \App\Repository\LanguageRepository())->getAll()  as $language)

                    <div class="form-group">
                        <label for="title{{$language->id}}">Title ({{$language->shortTitle}})</label>
                        <input value="{{$page->getTranslated($language)->title}}" type="text{{$language->id}}" name="title{{$language->id}}" id="title{{$language->id}}">
                    </div>


                    <div class="form-group">
                        <label for="description{{$language->id}}">Description</label>
                        <textarea name="description{{$language->id}}" id="description{{$language->id}}">{{$page->getTranslated($language)->description}}</textarea>
                    </div>
    @endforeach
                <br>
                <input type="submit" value="SUBMIT">
</form>

resources/views/index.blade.php
<ul>
    @foreach(\App\PageExtended::all() as $page)

<li>{{$page->getTranslated($defaultLanguage)->title}} <a href="{{route("pages.edit",["id"=>$page->id])}}">EDIT</a></li>

    @endforeach
</ul>

resources/views/menu-recursive.blade.php
<ul>
    @foreach($menus as $menu)
        <li>
            <a target="_blank" href="{{$menu["link"]}}">{{$menu["title"]}}</a>
            @if($menu["childs"])
                @include("menu-recursive",["menus"=>$menu["childs"]])
            @endif
        </li>
    @endforeach
</ul>

resources/views/menu.blade.php
<ul>
    @foreach($menus as $menu)
        <li>
                <a target="_blank" href="{{$menu["link"]}}">{{$menu["title"]}}</a>
                @foreach($menu["childs"] as $child)
                        <ul>
                                <li>
                                        <a target="_blank" href="{{$child["link"]}}">{{$child["title"]}}</a>
                                        @foreach($child["childs"] as $subChilds)
                                                <ul>
                                                        <li>
                                                                <a target="_blank" href="{{$subChilds["link"]}}">{{$subChilds["title"]}}</a>
                                                        </li>
                                                </ul>
                                        @endforeach
                                </li>
                        </ul>
                @endforeach
        </li>
    @endforeach
</ul>